name: Build, test and push container
on:
  schedule:
    - cron: 0 0 * * *
  # be able to start this action manually from a actions tab when needed
  workflow_dispatch:

jobs:
  refresh-container:
    name: Refresh anaconda-ci container
    runs-on: ubuntu-latest
    # we need to have matrix to cover all branches because schedule is run only on default branch
    # we can add here fedora branches (e.g. f33-devel) to cover their support when needed
    strategy:
      matrix:
        branch:
          - master
    steps:
      - name: Checkout anaconda repository
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - name: Build anaconda-ci container
        run: CONTAINER_ENGINE=docker make -f Makefile.am anaconda-ci-build

      - name: Run tests in anaconda-ci container
        id: run-tests
        run: CONTAINER_ENGINE=docker make -f Makefile.am container-ci
        continue-on-error: true

      - name: Upload test and coverage logs from local testing
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            tests/test-suite.log
            tests/nosetests.log
            tests/pylint/runpylint*.log
            tests/coverage-*.log

      - name: Fail if local test did not worked
        if: ${{ steps.run-tests.outcome == 'failure' }}
        run: |
          cat tests/test-suite.log
          exit 1

      - name: Login to container registry
        run: docker login -u ${{ secrets.QUAY_USERNAME }} -p ${{ secrets.QUAY_PASSWORD }} quay.io

        # we can hardcode the path to the image here because this will be executed only for master image
      - name: Add latest tag for master branch
        if: ${{ matrix.branch == 'master' }}
        run: |
          docker tag quay.io/rhinstaller/anaconda-ci:master quay.io/rhinstaller/anaconda-ci:latest
          CONTAINER_ENGINE=docker CI_TAG=latest make -f Makefile.am anaconda-ci-push

      - name: Push container to registry
        run: CONTAINER_ENGINE=docker make -f Makefile.am anaconda-ci-push
