name: Automate pot file creation
on: push

jobs:
  update-pot-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout anaconda
        uses: actions/checkout@v2
        with:
          path: anaconda
      - name: Create pot file
        uses: jkonecny12/anaconda-make-executor-action@v1-beta2
        with:
          make-command: pot-update-check
          path: anaconda
      - name: Checkout anaconda-l10n
        uses: actions/checkout@v2
        with:
          repository: jkonecny12/anaconda-l10n
          path: anaconda-l10n
      - name: Commit new pot file
        run: |
          cp -v anaconda/po/anaconda.pot anaconda-l10n/master/
          cd anaconda-l10n
          git config user.name InStallker
          git config user.email github-actions@github.com
          git add .
          git commit -m "update pot-file"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: anaconda-l10n
          github_token: ${{ secrets.INSTALLKER_TOKEN }}
          repository: jkonecny12/anaconda-l10n
