name: validate
on: [push, pull_request_target]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Check if container changed in this PR
        id: check-dockerfile-changed
        run: |
          git diff --name-only $GITHUB_BASE_REF $GITHUB_HEAD_REF | grep -q dockerfile/anaconda-ci/ || exit 1
        continue-on-error: true

      # build container if files for dockerfile changed in the PR
      - name: Build anaconda-ci container
        if: ${{ steps.check-dockefile-changed.outcome == 'success' }}
        run: CONTAINER_ENGINE=docker make -f Makefile.am anaconda-ci-build

      - name: Run tests in anaconda-ci container
        id: run-unit-tests
        run: CONTAINER_ENGINE=docker make -f Makefile.am container-ci
        continue-on-error: true

      - name: Upload test and coverage logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            tests/test-suite.log
            tests/nosetests.log
            tests/pylint/runpylint*.log
            tests/coverage-*.log

      - name: Set job result
        if: ${{ steps.run-unit-tests.outcome == 'failure' }}
        run: |
          cat tests/test-suite.log
          exit 1

  rpm-tests:
    runs-on: ubuntu-latest
    # start from a minimal container and install only our build deps; mock does
    # not work in an unprivileged container (no CAP_SYS_ADMIN for mount), and
    # dnf --installroot is too broken (rhbz#1885103, #1885101, #1738233)
    container:
      image: docker.io/fedora:rawhide
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: install build dependencies
        run: |
          dnf install -y /usr/bin/xargs
          scripts/testing/dependency_solver.py -b | xargs -d '\n' dnf install -y --setopt=install_weak_deps=False --nodocs rpm-build

      - name: build RPMs
        run: |
          ./autogen.sh
          ./configure
          make rpms

      - name: run RPM tests
        run: |
          make run-rpm-tests-only || { cat tests/rpm_tests.log; exit 1; }

      - name: test installability
        run: |
          dnf install -y result/build/01-rpm-build/*.rpm
